#!/bin/bash
#
# Stream-Pi - Free & Open-Source Modular Cross-Platform Programmable Macro Pad
# Copyright (C) 2019-2021  Debayan Sutradhar (rnayabed),  Samuel Quiñones (SamuelQuinones)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

cd "${0%/*}"
export ENABLE_GLUON_COMMERCIAL_EXTENSIONS=true
export DISPLAY_CARD0=/dev/dri/card0
export DISPLAY_CARD1=/dev/dri/card1 # For Raspberry Pi 4

if ! jre/bin/java -Xmx700m -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verbose=true -Dprism.lcdtext=false -Dprism.verbose=true -Dcom.sun.javafx.virtualKeyboard=javafx -Dembedded=monocle -Dglass.platform=Monocle -Dmonocle.platform=EGL -Djava.library.path=. -Dmonocle.egl.lib=./libgluon_drm.so -Degl.displayid=$DISPLAY_CARD0 --module-path . --add-modules ALL-MODULE-PATH com.stream_pi.client.Main Stream-Pi.enableScreenSaverFeature=true Stream-Pi.showShutDownButton=true Stream-Pi.startupRunnerFileName=run_console Stream-Pi.isXMode=false Stream-Pi.isShowFullScreenToggleButton=false Stream-Pi.defaultFullScreenMode=true; then
	echo failed to launch using card0, trying to launch using card1
	
	if ! jre/bin/java -Xmx700m -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verbose=true -Dprism.lcdtext=false -Dprism.verbose=true -Dcom.sun.javafx.virtualKeyboard=javafx -Dembedded=monocle -Dglass.platform=Monocle -Dmonocle.platform=EGL -Djava.library.path=. -Dmonocle.egl.lib=./libgluon_drm.so -Degl.displayid=$DISPLAY_CARD1 --module-path . --add-modules ALL-MODULE-PATH com.stream_pi.client.Main Stream-Pi.enableScreenSaverFeature=true Stream-Pi.showShutDownButton=true Stream-Pi.startupRunnerFileName=run_console Stream-Pi.isXMode=false Stream-Pi.isShowFullScreenToggleButton=false Stream-Pi.defaultFullScreenMode=true; then
		echo failed to launch using card1. Is your KMS driver turned on?
	else
		echo success using card1
	fi
else
	echo success using card0
fi

