#!/bin/bash
cd "${0%/*}"

DISPLAY=:0 ./client -Djavafx.platform=gtk -Djavafx.verbose=true -Dprism.verbose=true -Dcom.sun.javafx.isEmbedded=true -Dcom.sun.javafx.virtualKeyboard=javafx -DStream-Pi.showShutDownButton=true -DStream-Pi.startupRunnerFileName=run_desktop -DStream-Pi.isXMode=true -DStream-Pi.defaultFullScreenMode=true
