#!/bin/bash
cd "${0%/*}"
export ENABLE_GLUON_COMMERCIAL_EXTENSIONS=true
export DISPLAY_CARD0=/dev/dri/card0
export DISPLAY_CARD1=/dev/dri/card1 # For Raspberry Pi 4

if ! ./client -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verbose=true -Dprism.verbose=true -Dcom.sun.javafx.virtualKeyboard=javafx -Dembedded=monocle -Dmonocle.platform=EGL -Djava.library.path=. -Dmonocle.egl.lib=./libgluon_drm.so -Degl.displayid=$DISPLAY_CARD0 -DStream-Pi.enableScreenSaverFeature=true -DStream-Pi.showShutDownButton=true -DStream-Pi.startupRunnerFileName=run_console -DStream-Pi.isXMode=false -DStream-Pi.isShowFullScreenToggleButton=false -DStream-Pi.defaultFullScreenMode=true; then
	echo failed to launch using card0, trying to launch using card1
	
	if ! ./client -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verbose=true -Dprism.verbose=true -Dcom.sun.javafx.virtualKeyboard=javafx -Dembedded=monocle -Dmonocle.platform=EGL -Djava.library.path=. -Dmonocle.egl.lib=./libgluon_drm.so -Degl.displayid=$DISPLAY_CARD1 -DStream-Pi.enableScreenSaverFeature=true -DStream-Pi.showShutDownButton=true -DStream-Pi.startupRunnerFileName=run_console -DStream-Pi.isXMode=false -DStream-Pi.isShowFullScreenToggleButton=false -DStream-Pi.defaultFullScreenMode=true; then
		echo failed to launch using card1. Is your KMS driver turned on?
	else
		echo success using card1
	fi
else
	echo success using card0
fi

