#!/bin/bash
cd "${0%/*}"

DISPLAY=:0 ./client -Djavafx.platform=gtk -Djavafx.verbose=true -Dprism.verbose=true -Dcom.sun.javafx.isEmbedded=true -Dcom.sun.javafx.virtualKeyboard=javafx Stream-Pi.showShutDownButton=true Stream-Pi.startupRunnerFileName=run_desktop Stream-Pi.isXMode=true Stream-Pi.defaultFullScreenMode=true
