#!/bin/bash
cd "${0%/*}"
export ENABLE_GLUON_COMMERCIAL_EXTENSIONS=true
export DISPLAY_CARD0=/dev/dri/card0
export DISPLAY_CARD1=/dev/dri/card1 # For Raspberry Pi 4

if ! jre/bin/java -Xmx700m -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verbose=true -Dprism.verbose=true -Dcom.sun.javafx.virtualKeyboard=javafx -Dembedded=monocle -Dglass.platform=Monocle -Dmonocle.platform=EGL -Djava.library.path=. -Dmonocle.egl.lib=./libgluon_drm.so -Degl.displayid=$DISPLAY_CARD0 --module-path . --add-modules ALL-MODULE-PATH com.stream_pi.client.Main Stream-Pi.enableScreenSaverFeature=true Stream-Pi.showShutDownButton=true Stream-Pi.startupRunnerFileName=run_console Stream-Pi.isXMode=false Stream-Pi.isShowFullScreenToggleButton=false Stream-Pi.defaultFullScreenMode=true; then
	echo failed to launch using card0, trying to launch using card1
	
	if ! jre/bin/java -Xmx700m -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.isEmbedded=true -Djavafx.verbose=true -Dprism.verbose=true -Dcom.sun.javafx.virtualKeyboard=javafx -Dembedded=monocle -Dglass.platform=Monocle -Dmonocle.platform=EGL -Djava.library.path=. -Dmonocle.egl.lib=./libgluon_drm.so -Degl.displayid=$DISPLAY_CARD1 --module-path . --add-modules ALL-MODULE-PATH com.stream_pi.client.Main Stream-Pi.enableScreenSaverFeature=true Stream-Pi.showShutDownButton=true Stream-Pi.startupRunnerFileName=run_console Stream-Pi.isXMode=false Stream-Pi.isShowFullScreenToggleButton=false Stream-Pi.defaultFullScreenMode=true; then
		echo failed to launch using card1. Is your KMS driver turned on?
	else
		echo success using card1
	fi
else
	echo success using card0
fi

