name: Init

on:
  push:
    branches:
      - master

jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
      - name: Install packages
        run: sudo apt install unzip axel
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          architecture: x64
      - name: Setup JavaFX
        run: |
          cd /tmp
          axel -n 8 https://download2.gluonhq.com/openjfx/18/openjfx-18-ea+11_linux-x64_bin-sdk.zip
          unzip /tmp/openjfx-18-ea+11_linux-x64_bin-sdk.zip -d /tmp
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Kolkata"
      - name: Build Jars
        run: mvn -X package
      - name: Save built jars
        uses: actions/upload-artifact@v2
        with:
          name: built-jars
          path: target/lib/*
      - name: Set Version
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Set Build Number
        run: |
          RAW_BUILD_NUMBER=$(sed '4q;d' src/main/resources/com/stream_pi/client/info/build.properties)
          echo "BUILD_NUMBER=${RAW_BUILD_NUMBER#*=}" >> $GITHUB_ENV
      - name: Calculate required modules
        run: |
          JDEPS_MODULES=$(jdeps --module-path $JAVAFX_SDK/:target/lib/ --print-module-deps --ignore-missing-deps target/lib/client-$VERSION.jar)
          echo "REQ_MODULES=$JDEPS_MODULES" >> $GITHUB_ENV
        env:
          JAVAFX_SDK: /tmp/javafx-sdk-18/lib/
      - name: Saving REQ_MODULES
        run: |
          echo $REQ_MODULES > req_modules.txt
      - name: Uploading REQ_MODULES
        uses: actions/upload-artifact@v2
        with:
          name: req_modules
          path: req_modules.txt
      - name: Saving VERSION
        run: |
          echo $VERSION > version.txt
      - name: Uploading VERSION
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
      - name: Saving BUILD_NUMBER
        run: |
          echo $BUILD_NUMBER > build_number.txt
      - name: Uploading BUILD_NUMBER
        uses: actions/upload-artifact@v2
        with:
          name: build_number
          path: build_number.txt
